export const FETCH_LOGIN_USER_REQUEST = "FETCH_LOGIN_USER_REQUEST";
export const FETCH_LOGIN_USER_SUCCESS = "FETCH_LOGIN_USER_SUCCESS";
export const FETCH_LOGIN_USER_FAILURE = "FETCH_LOGIN_USER_FAIILURE";
export const FETCH_LOGOUT_USER_REQUEST = "FETCH_LOGOUT_USER_REQUEST";
